# Generated by Django 3.1.1 on 2020-09-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsLevel', models.PositiveIntegerField(default=0)),
                ('countCompletedTasks', models.PositiveIntegerField(default=0)),
                ('countFailedTasks', models.PositiveIntegerField(default=0)),
                ('statistic_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=100)),
                ('taskDesc', models.TextField()),
                ('deadlineDate', models.DateField(blank=True)),
                ('priority', models.PositiveIntegerField()),
                ('complexity', models.PositiveIntegerField()),
                ('task_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
