export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_USERNAME_FAIL = "CHANGE_USERNAME_FAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ENABLE_NOTIFY = "ENABLE_NOTIFY";
export const DISABLE_NOTIFY = "DISABLE_NOTIFY";

export const ADD_TASK = "ADD_TASK";
export const GET_TASKS = "GET_TASKS";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_TASK = "CHANGE_TASK";

export const COMPLETE_TASK = "COMPLETE_TASK";
export const FAIL_TASK = "FAIL_TASK";

export const GET_STATISTIC = "GET_STATISTIC";
export const CREATE_STATISTIC = "CREATE_STATISTIC";
export const CREATE_STATISTIC_FAIL = "CREATE_STATISTIC_FAIL";

export const GET_RATING_USERS = "GET_RATING_USERS";
